#pragma config(Sensor, in1,    armpot,         sensorPotentiometer)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           clawRotate,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           nod,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int potential;
int turnSequence;
int highBar;
task main()
{
	while (true) {
		potential = (SensorValue(armpot));

		//drive
		motor[port2] = vexRT[Ch3] + vexRT[Ch4];
		motor[port3] = vexRT[Ch3] - vexRT[Ch4];

		//4-bar arm
		motor[port7] = vexRT[Ch2];
		motor[port8] = vexRT[Ch2];

		//nod
		motor[port9] = 127*(vexRT[Btn5U] - vexRT[Btn5D]);

		//cap rotation
		motor[port5] = 127*(vexRT[Btn6U] - vexRT[Btn6D]);

		//ball intake
		//motor [port4]


		//flywheel, puncher, or catapult
		//rotatebutton
		if (vexRT[Btn7U]) {
	highBar = true;
}
		if (highBar == true) {
motor[arm1] = -127;
motor[arm2] = -127;
if (potential > 1000){
motor[arm1] = 0;
motor[arm2] = 0;
}
}

		if (vexRT[Btn8U]) {
	turnSequence = true;
}
		if (turnSequence == true)
motor[port5] = 32;
wait1Msec(1625);
motor[port5] = 0;
turnSequence = false;
		}
	}
