#pragma config(Sensor, in4,    nodpot,         sensorPotentiometer)
#pragma config(Sensor, in5,    armpot,         sensorPotentiometer)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           punch,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawRotate,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           nod,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[leftDrive] = 127;
motor[rightDrive] = 127;
motor[nod] = -127;
wait1Msec(1750);
motor[clawRotate] = 127;
wait1Msec(700);
motor[clawRotate] = 0;
motor[leftDrive] = 0;
motor[rightDrive] = 0;
wait1Msec(500);
motor[nod] = 0;
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
int barpot;
int tippot;
int turnSequence;
int highBar;
int lowBar;
int hightolowBar;
int hightohighBar;
int highBarExactgoup;
int highBarExactgodown;
int lowBarExactgoup;
int lowBarExactgodown;

int tmpauton;
  while (true)
  {		barpot = (SensorValue(armpot));
		tippot = (SensorValue(nodpot));

if (tmpauton != true) {
		//drive
		motor[leftDrive] = vexRT[Ch3] + vexRT[Ch4];
		motor[rightDrive] = vexRT[Ch3] - vexRT[Ch4];

		//4-bar arm
		if (highBar == false && lowBar == false && hightolowBar == false && hightohighBar == false && highBarExactgodown == false && highBarExactgoup == false && lowBarExactgodown == false && lowBarExactgoup == false) {
		motor[arm1] = vexRT[Ch3Xmtr2];
		motor[arm2] = vexRT[Ch3Xmtr2];
	}

		//nod
		motor[nod] = 127*(vexRT[Btn5UXmtr2] - vexRT[Btn5DXmtr2]);

		//cap rotation
		motor[clawRotate] = 127*(vexRT[Btn6UXmtr2] - vexRT[Btn6DXmtr2]);

		//ball intake
		motor[intake] = 127*(vexRT[Btn7U] - vexRT[Btn7D]);


		//flywheel, puncher, or catapult
		motor[punch] = 127*(vexRT[Btn8U] - vexRT[Btn8D]);
}
/*
____________________________________________________________________________
 Automation
____________________________________________________________________________
*/



	//temp auton test
/*	if (vexRT[Btn7R]) {
	tmpauton = true;
}
if (tmpauton == true) {
motor[leftDrive] = -127;
motor[rightDrive] = -127;
motor[nod] = -127;
wait1Msec(2750);
motor[leftDrive] = 0;
motor[rightDrive] = 0;
wait1Msec(500);
motor[nod] = 0;

motor[clawRotate] = 127;
wait1Msec(700);
motor[clawRotate] = 0;
tmpauton = false;
}
*/







		//STOP THE AUTON
		if (vexRT[Btn7LXmtr2]) {
			lowBar = false;
			highBar = false;
			hightolowBar = false;
			hightohighBar = false;
			highBarExactgoup = false;
			highBarExactgodown = false;
			lowBarExactgoup = false;
			lowBarExactgodown = false;
	}


		//low bar button
		if (vexRT[Btn8RXmtr2]) {
			if (barpot < 1500) {
				lowBar = true;
			}
			if (barpot > 1500) {
				hightolowBar = true;
		}
	}

		if (lowBar == true) {
			motor[arm1] = (1700 - barpot)/3;
			motor[arm2] = (1700 - barpot)/3;
			if (barpot > 1500) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				lowBar = false;
			}
		}

		if (hightolowBar == true) {
			motor[arm1] = (1300 - barpot)/3;
			motor[arm2] = (1300 - barpot)/3;
			if (barpot < 1500) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				hightolowBar = false;
		}
	}

		//low bar exact
		if (vexRT[Btn8DXmtr2]) {
			if (barpot < 1100) {
				lowBarExactgoup = true;
			}
			if (barpot > 1100) {
				lowBarExactgodown = true;
			}
		}

		if (lowBarExactgoup == true) {
			motor[arm1] = (1300 - barpot)/3;
			motor[arm2] = (1300 - barpot)/3;
			if (barpot > 1100) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				lowBarExactgoup = false;
			}
		}

		if (lowBarExactgodown == true) {
			motor[arm1] = (900 - barpot)/3;
			motor[arm2] = (900 - barpot)/3;
			if (barpot < 1100) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				lowBarExactgodown = false;
			}
		}

		//high bar button
		if (vexRT[Btn8UXmtr2]) {
			if (barpot < 1500) {
			highBar = true;
		}
			if (barpot > 1500) {
			hightohighBar = true;
		}
	}
		if (highBar == true) {
			motor[arm1] = (1700 - barpot)/3;
			motor[arm2] = (1700 - barpot)/3;
			if (barpot > 1500) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				highBar = false;
			}
		}

		if (hightohighBar == true) {
			motor[arm1] = (1300 - barpot)/3;
			motor[arm2] = (1300 - barpot)/3;
			if (barpot < 1500) {
				motor[arm1] = 0;
				motor[arm2] = 0;
				hightohighBar = false;
		}
	}

	//high bar exact
	  if (vexRT[Btn8LXmtr2]) {
	 		if (barpot < 1400) {
	   		highBarExactgoup = true;
	 }
	 		if (barpot > 1400) {
	 				highBarExactgodown = true;
	 	}
	}

	if (highBarExactgoup == true) {
		motor[arm1] = (1600 - barpot)/3;
		motor[arm2] = (1600 - barpot)/3;
		if (barpot > 1400) {
			motor[arm1] = 0;
			motor[arm2] = 0;
			highBarExactgoup = false;
		}
	}
	if (highBarExactgodown == true) {
		motor[arm1] = (1200 - barpot)/3;
		motor[arm2] = (1200 - barpot)/3;
		if (barpot < 1400) {
			motor[arm1] = 0;
			motor[arm2] = 0;
			highBarExactgodown = false;
		}
	}

		//rotatebutton
		if (vexRT[Btn7UXmtr2]) {
			turnSequence = true;
		}
		if (turnSequence == true) {
			motor[clawRotate] = 127;
			wait1Msec(1400);
			motor[clawRotate] = 0;
			turnSequence = false;
		}

    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
  }
}
